name: template_example
description: Example usage of package:template.
version: 0.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spectrum: ^0.2.1+1
  url_launcher: ^6.0.9

dev_dependencies:
  template:
    path: ../

flutter:
  uses-material-design: true
